global_costmap:
    plugins: 
        - {name: navigation_map, type: "costmap_2d::StaticLayer" }
        - {name: obstacles,  type: "costmap_2d::ObstacleLayer" }
        # - {name: virtual_walls, type: "costmap_2d::StaticLayer" }
        # - {name: costmap_prohibition_layer, type: 'costmap_prohibition_layer_namespace::CostmapProhibitionLayer'}
        - {name: inflation,  type: "costmap_2d::InflationLayer" }
        # - {name: prefer_zone, type: "costmap_2d::StaticLayer" }
        # - {name: not_prefer_zone, type: "costmap_2d::StaticLayer" }
