base_global_planner: pub_planner/PubPlanner #global_planner/GlobalPlanner
GlobalPlanner:
  allow_unknown: false
  default_tolerance: 0.0
  visualize_potential: false
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behaviour: false

  lethal_cost: 253
  neutral_cost: 50
  cost_factor: 3

  publish_potential: false
  orientation_mode: 1 #(None=0, Forward=1, Interpolate=2, ForwardThenInterpolate=3, Backward=4, Leftward=5, Rightward=6)
  orientation_window_size: 1
